# Generated by Django 3.0.5 on 2020-06-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200626_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genere',
            new_name='genre',
        ),
    ]
