# Generated by Django 3.0.5 on 2020-06-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200626_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gener',
            new_name='Genre',
        ),
    ]
